image: python:3.12

stages:
  - test

selenium-tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg unzip xvfb
    # Install Chrome dependencies
    - apt-get install -y \
        libnss3 \
        libatk1.0-0 \
        libcups2 \
        libxss1 \
        libxcomposite1 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libgtk-3-0

    # Install Google Chrome
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get install -y ./google-chrome-stable_current_amd64.deb --fix-broken

    # Install Python dependencies
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - pytest -v

